name = "aiken-lang/hello-world"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/hello-world'"

user = "aiken-lang"
project = "hello-world"
platform = "github"

name = "aiken-lang/stdlib"
version = "v2"
source = "github"